Use XDG standard location for binaries in setup script
baalimago/wd-41 pull request #5
Opened 2024-09-06 01:29 UTC by secureshellprotocol

Following [XDG standard](https://specifications.freedesktop.org/basedir-spec/latest/), I changed the default install location to `$HOME/.local/bin`. It can retain the old location if ran as root.

2024-09-06 01:33 UTC, secureshellprotocol commented
It might be useful to add more flags to the script, maybe one for changing where our binary installs to, so someone could specify a custom location.
However, since the `README` recommends `curl`ing the script, there's no obvious way to use the flag besides ignoring that and just cloning the repo to run the script in the shell, specifying the flag there. So, I didn't add it to the script

2024-09-07 20:10 UTC, baalimago requested changes
Ah, I didn't know about this XDG standard.

The idea with the setup script is to make it as plug-and-play as possible, simply to copy-paste the script and then have wd-41 installed without any fuzz. So with this in mind your suggestions are a great addition, many thanks!

2024-09-07 20:10 UTC, baalimago commented on setup.sh
> +if [ $EUID -eq 0 ]; then
This didn't work on my machine, I suspect that `EUID` is a variable added in bash:
```bash
(zsh)❯ echo $EUID
1000
❯ sh
$ echo $EUID
(empty-string)
```

Doing it this way worked though:
```shell
if [ "$(id -u)" -eq 0 ]; then
	INSTALL_DIR=/usr/local/bin
fi
```

2024-09-08 21:53 UTC, secureshellprotocol commented
Ah, I guess I took `$EUID` for granted. In my `/etc/profile`, by default it sets that variable using `/usr/bin/id -u` (on Fedora 40), so I see it in my `sh` shell

I implemented your change (plus a check to see if `id` is present). Both methods appear to work on my end: invoking it from the shell, and `curl`-piping into `sh`.

> The idea with the setup script is to make it as plug-and-play as possible, simply to copy-paste the script and then have wd-41 installed without any fuzz.  

Makes sense, flags are not the right approach in that case. Perhaps it could be interactive, with the script prompting for a path and giving the option to use a default path (in this case, the XDG bin path).

2024-09-09 16:05 UTC, baalimago approved these changes
Very nice, works like a charm!

Regarding prompting the user for a location to store the binary: it's also a good improvement! But this solution is good enough for now I think. Especially since the binary is printed the user may move it if wanted.

Thanks for the addition!

2024-09-09 16:07 UTC, merged